apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: speedrunners-leesah-game
  namespace: leesah-quiz
  labels:
    team: leesah-quiz
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    initialDelay: 30
    path: /isalive
  readiness:
    initialDelay: 30
    path: /isready
  replicas:
    min: 1
    max: 1
  kafka:
    pool: nav-dev
  prometheus:
    enabled: true
    path: /metrics
  env:
    - name: QUIZ_TOPIC
      value: "leesah-quiz.leesah-rapid-v2"
